export type SourceBook = 'business_vocab_advanced' | 'ict_in_use';

export type LessonSeed = {
  number: number;
  title: string;
  sourceBook: SourceBook;
  level: 'B1' | 'B2' | 'C1';
  vocabCategory: string;
  vocabTheme: string;
  grammarTopicName: string;
  speakingPrompt: string;
};

export const LESSON_CURRICULUM: LessonSeed[] = [
  {
    number: 1,
    title: 'Company Structure and Roles',
    sourceBook: 'business_vocab_advanced',
    level: 'B1',
    vocabCategory: 'lesson-01-company-structure',
    vocabTheme: 'departments, job titles, and reporting lines in a company',
    grammarTopicName: 'Present Perfect vs Past Simple',
    speakingPrompt: "Describe your own team's structure and who you report to.",
  },
  {
    number: 2,
    title: 'Networks and Connectivity',
    sourceBook: 'ict_in_use',
    level: 'B1',
    vocabCategory: 'lesson-02-networks',
    vocabTheme: 'LANs, WANs, routers, bandwidth, and connecting devices',
    grammarTopicName: 'First Conditional',
    speakingPrompt: "Explain what happens if your office Wi-Fi goes down and how you'd troubleshoot it.",
  },
  {
    number: 3,
    title: 'Negotiating Deals',
    sourceBook: 'business_vocab_advanced',
    level: 'B1',
    vocabCategory: 'lesson-03-negotiating',
    vocabTheme: 'concessions, deadlines, and counter-offers in a negotiation',
    grammarTopicName: 'Second Conditional',
    speakingPrompt: 'Describe how you would negotiate a tighter deadline with a client.',
  },
  {
    number: 4,
    title: 'Email and Online Communication',
    sourceBook: 'ict_in_use',
    level: 'B1',
    vocabCategory: 'lesson-04-email',
    vocabTheme: 'email etiquette, CC/BCC, attachments, and netiquette',
    grammarTopicName: 'Modals of Obligation',
    speakingPrompt: 'Explain the rules you follow for writing a professional email at work.',
  },
  {
    number: 5,
    title: 'Marketing and Branding',
    sourceBook: 'business_vocab_advanced',
    level: 'B1',
    vocabCategory: 'lesson-05-marketing',
    vocabTheme: 'brand positioning, target audience, and campaigns',
    grammarTopicName: 'Comparatives and Superlatives',
    speakingPrompt: 'Compare two products or services you know well in terms of how they are marketed.',
  },
  {
    number: 6,
    title: 'Hardware and Devices',
    sourceBook: 'ict_in_use',
    level: 'B1',
    vocabCategory: 'lesson-06-hardware',
    vocabTheme: 'computer components, peripherals, and storage devices',
    grammarTopicName: 'Present Continuous for Future Arrangements',
    speakingPrompt: "Describe what new hardware you're planning to set up or buy soon.",
  },
  {
    number: 7,
    title: 'Recruitment and Hiring',
    sourceBook: 'business_vocab_advanced',
    level: 'B1',
    vocabCategory: 'lesson-07-recruitment',
    vocabTheme: 'job postings, interviews, and onboarding',
    grammarTopicName: 'Used to / Would for Past Habits',
    speakingPrompt: 'Talk about how hiring used to work at a previous job compared to now.',
  },
  {
    number: 8,
    title: 'Software and Applications',
    sourceBook: 'ict_in_use',
    level: 'B1',
    vocabCategory: 'lesson-08-software',
    vocabTheme: 'installing, updating, and licensing software',
    grammarTopicName: 'Passive Voice (Simple Tenses)',
    speakingPrompt: 'Describe how a piece of software you use every day gets installed and updated.',
  },
  {
    number: 9,
    title: 'Mergers and Acquisitions',
    sourceBook: 'business_vocab_advanced',
    level: 'B2',
    vocabCategory: 'lesson-09-mergers',
    vocabTheme: 'acquisitions, stakeholders, and due diligence',
    grammarTopicName: 'Third Conditional',
    speakingPrompt: 'Describe what would have happened if a recent deal you know of had fallen through.',
  },
  {
    number: 10,
    title: 'Technical Support and Troubleshooting',
    sourceBook: 'ict_in_use',
    level: 'B2',
    vocabCategory: 'lesson-10-tech-support',
    vocabTheme: 'reporting bugs, escalation, and support tickets',
    grammarTopicName: 'Reported Speech',
    speakingPrompt: 'Report what a colleague told you about a recent technical issue.',
  },
  {
    number: 11,
    title: 'Finance and Budgeting',
    sourceBook: 'business_vocab_advanced',
    level: 'B2',
    vocabCategory: 'lesson-11-finance',
    vocabTheme: 'budgets, forecasts, and cost control',
    grammarTopicName: 'Relative Clauses',
    speakingPrompt: 'Describe a budget decision at work that affected the team you work with.',
  },
  {
    number: 12,
    title: 'Databases and Data Management',
    sourceBook: 'ict_in_use',
    level: 'B2',
    vocabCategory: 'lesson-12-databases',
    vocabTheme: 'tables, queries, backups, and data integrity',
    grammarTopicName: 'Passive Voice (All Tenses)',
    speakingPrompt: 'Explain how data is stored and backed up in a system you work with.',
  },
  {
    number: 13,
    title: 'Risk and Compliance',
    sourceBook: 'business_vocab_advanced',
    level: 'B2',
    vocabCategory: 'lesson-13-risk-compliance',
    vocabTheme: 'regulations, audits, and liability',
    grammarTopicName: 'Modals of Deduction',
    speakingPrompt: 'Speculate about what might have caused a compliance issue you have heard about.',
  },
  {
    number: 14,
    title: 'Web Design and User Experience',
    sourceBook: 'ict_in_use',
    level: 'B2',
    vocabCategory: 'lesson-14-web-design',
    vocabTheme: 'layout, usability, responsive design, and accessibility',
    grammarTopicName: 'Gerunds vs Infinitives',
    speakingPrompt: 'Describe what you enjoy and dislike about designing or using a particular website.',
  },
  {
    number: 15,
    title: 'Supply Chain and Logistics',
    sourceBook: 'business_vocab_advanced',
    level: 'B2',
    vocabCategory: 'lesson-15-supply-chain',
    vocabTheme: 'suppliers, inventory, and shipping',
    grammarTopicName: 'Articles',
    speakingPrompt: 'Describe a supply chain delay you have experienced or heard about.',
  },
  {
    number: 16,
    title: 'Cybersecurity and Data Protection',
    sourceBook: 'ict_in_use',
    level: 'B2',
    vocabCategory: 'lesson-16-cybersecurity',
    vocabTheme: 'encryption, phishing, firewalls, and data breaches',
    grammarTopicName: 'Mixed Conditionals',
    speakingPrompt: 'Discuss what you would do differently now if your company had had a data breach last year.',
  },
  {
    number: 17,
    title: 'Corporate Strategy and Leadership',
    sourceBook: 'business_vocab_advanced',
    level: 'C1',
    vocabCategory: 'lesson-17-strategy',
    vocabTheme: 'vision, stakeholder alignment, and long-term planning',
    grammarTopicName: 'Inversion for Emphasis',
    speakingPrompt: "Describe a leadership decision you've rarely seen handled well, and why.",
  },
  {
    number: 18,
    title: 'Cloud Computing and Infrastructure',
    sourceBook: 'ict_in_use',
    level: 'C1',
    vocabCategory: 'lesson-18-cloud',
    vocabTheme: 'scaling, uptime, hosting, and cloud providers',
    grammarTopicName: 'Cleft Sentences',
    speakingPrompt: 'Explain what it was that convinced your team to move to the cloud (real or hypothetical).',
  },
  {
    number: 19,
    title: 'Crisis Management and PR',
    sourceBook: 'business_vocab_advanced',
    level: 'C1',
    vocabCategory: 'lesson-19-crisis-pr',
    vocabTheme: 'damage control, public statements, and reputation',
    grammarTopicName: 'Subjunctive Mood',
    speakingPrompt: 'Suggest what a company should do after a public relations crisis.',
  },
  {
    number: 20,
    title: 'Agile Development and Project Management',
    sourceBook: 'ict_in_use',
    level: 'C1',
    vocabCategory: 'lesson-20-agile',
    vocabTheme: 'sprints, standups, backlogs, and retrospectives',
    grammarTopicName: 'Advanced Modals of Criticism',
    speakingPrompt: 'Criticize a project process that could have been planned better, and explain why.',
  },
  {
    number: 21,
    title: 'International Business and Globalization',
    sourceBook: 'business_vocab_advanced',
    level: 'C1',
    vocabCategory: 'lesson-21-international-business',
    vocabTheme: 'market entry, localization, and cross-border trade',
    grammarTopicName: 'Participle Clauses',
    speakingPrompt: 'Describe the challenges a company faces when expanding into a new country.',
  },
  {
    number: 22,
    title: 'Artificial Intelligence and Automation',
    sourceBook: 'ict_in_use',
    level: 'C1',
    vocabCategory: 'lesson-22-ai-automation',
    vocabTheme: 'machine learning, automation, and AI tools at work',
    grammarTopicName: 'Ellipsis and Substitution',
    speakingPrompt: 'Discuss whether AI tools have changed how you work, and how.',
  },
  {
    number: 23,
    title: 'Innovation and Change Management',
    sourceBook: 'business_vocab_advanced',
    level: 'C1',
    vocabCategory: 'lesson-23-innovation',
    vocabTheme: 'disruption, pilot projects, and organizational change',
    grammarTopicName: 'Nuanced Prepositions',
    speakingPrompt: 'Describe a change at your company that people were initially resistant to.',
  },
  {
    number: 24,
    title: 'Software Architecture and Scalability',
    sourceBook: 'ict_in_use',
    level: 'C1',
    vocabCategory: 'lesson-24-architecture',
    vocabTheme: 'microservices, scalability, technical debt, and system design',
    grammarTopicName: 'Discourse Markers and Hedging',
    speakingPrompt: "Explain a system design trade-off your team has debated, hedging where you're not fully certain.",
  },
];
